# The Docker image that will be used to build your app
image: ubuntu:22.04
pages:
  before_script:
    - apt update
    - apt -y install git hugo tree
  script:
    - |
      set -x
      git fetch --all
      git checkout $CI_COMMIT_REF_NAME

      mkdir public_all

      export BRANCHES=$(git branch -a --format='%(refname:short)' | cut -d'/' -f 2 | sort -u | grep -v origin)
      for branch in $BRANCHES;
      do
        echo $branch
        git checkout $branch
        hugo
        mkdir -p public_all/$CI_COMMIT_REF_NAME
        cp -a public/* public_all/$CI_COMMIT_REF_NAME/
      done

      git checkout $CI_DEFAULT_BRANCH
      hugo
      cp -r public/* public_all/
      rm -rf public/
      mv public_all public
      tree -L 5 public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
