image: archlinux
pages:
  before_script:
    - pacman -Syy
    - pacman -S --noconfirm hugo
  script: hugo
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
