# The Docker image that will be used to build your app
image: ubuntu:22.04
pages:
  before_script:
    - apt update
    - apt -y install git hugo
  script:
    - |
      set -x
      git fetch --all
      git checkout $CI_COMMIT_REF_NAME

      mkdir public_all

      export BRANCHES=$(git branch --list --format='%(refname:short)')
      for branch in $BRANCHES;
      do
        echo $branch
        git checkout $branch
        hugo
        mv public public_all/$CI_COMMIT_REF_NAME
      done

      git checkout $CI_DEFAULT_BRANCH
      hugo
      cp -a public/* public_all/
      rm -rf public/
      mv public_all public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
