# The Docker image that will be used to build your app
image: ubuntu:22.04
pages:
  before_script:
    - apt update
    - apt -y install git hugo
  script: hugo
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
