baseURL = "https://next.distro.watch"
languageCode = "en-us"
title = "concrete box ramblings"

[author]
	name = "inherently"

[markup]
	[markup.highlight]
		anchorLineNos = true
		codeFences = true
		guessSyntax = true
		hl_Lines = ""
		lineAnchors = ""
		lineNoStart = 1
		lineNos = true
		lineNumbersInTable = true
		noClasses = true
		style = "native"
		tabWidth = 4
		lineOs = "table"
